name: Run Tests
on: push

jobs:
  build:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go-version:
          - 1.11.x
          - 1.12.x
          - 1.13.x
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v1
        if: matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.13.x'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
